Repository H-Iwase/kapanoruninupane, pull requests merged in 2018-05, with the labels that each got.

#3 Changed port number for koyajima
  run_tensorflow.sh
Labels: bug, help wanted

#6 test
  LICENSE
Labels: enhancement

#11 Changed jupyter port inside container to 9987 (same as host port)
  Dockerfile
  run_tensorflow.sh
Labels: bug
